"""empty message

Revision ID: 01a5edb12859
Revises: 
Create Date: 2017-09-19 20:17:17.239067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a5edb12859'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_detail',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('uname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('category',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('expense',
    sa.Column('expenseid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user_detail.email'], ),
    sa.PrimaryKeyConstraint('expenseid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('category')
    op.drop_table('user_detail')
    # ### end Alembic commands ###
